language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t cgjonesdev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cgjonesdev/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-450511817681"
    bucket_path: "resources"
    on:
        branch: "master"
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
